---
name: Build container images

on:
  push:
  pull_request:
    branches: [develop]
  merge_group:

jobs:
  build_containers:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    env:
      # Check if this is not a pull request and GITHUB_TOKEN is set
      # As all env variables are strings, you need to compare
      # against "== 'true'" (not "== true")
      IS_NOT_PR: "${{ !github.head_ref && true }}"
    steps:
      - name: Checkout Sample-Server
        uses: actions/checkout@v6.0.2
        with:
          path: Sample-Server
          submodules: recursive
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0
      - name: PrepareReg Names
        run: |
          echo IMAGE_REPOSITORY="$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.7.0
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Container Meta Data
        uses: docker/metadata-action@v5.10.0
        id: docker_meta
        with:
          images: ghcr.io/${{ env.IMAGE_REPOSITORY }}
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Build and push
        uses: docker/build-push-action@v6.19.2
        with:
          provenance: false
          file: "./Sample-Server/Dockerfile"
          context: ./Sample-Server
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.docker_meta.outputs.version }}
